#general dialog-vision Action signature

#goal
dialogsystem_msgs/DialogVisionMsg data_in

---

#result
dialogsystem_msgs/DialogVisionMsg data_out

---

#Feedback
dialogsystem_msgs/DialogVisionMsg feedback


